import { readdir, readFile, mkdir, rm, writeFile } from 'node:fs/promises';
import { resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transform } from '@svgr/core';

const SVG_EXTENSION = /\.svg$/i;
const BLACK = /^(?:black|#000|#000000|rgb\(\s*0\s*[, ]\s*0\s*[, ]\s*0\s*\))$/i;
const KEEP_PAINT = /^(?:none|transparent|currentColor|inherit|context-fill|context-stroke|url\(.*\))$/i;
const PAINT_ATTRIBUTE = /\b(fill|stroke|stop-color|flood-color|lighting-color)\s*=\s*(["'])(.*?)\2/gi;

export function componentName(filename) {
  const stem = basename(filename).replace(SVG_EXTENSION, '');
  if (!/^[a-zA-Z0-9]+(?:[-_ ][a-zA-Z0-9]+)*$/.test(stem)) {
    throw new Error(`Use letters, digits, hyphens, underscores or spaces in SVG names: ${filename}`);
  }
  return 'Ad' + stem.split(/[-_ ]/).map(word => word[0].toUpperCase() + word.slice(1)).join('');
}

function replaceOrThrow(code, pattern, replacement, what) {
  const result = code.replace(pattern, replacement);
  if (result === code) throw new Error(`SVGR output no longer matches the expected shape (${what}). Update scripts/generate.mjs.`);
  return result;
}

// Black ink becomes currentColor so icons follow the CSS text colour. Any other
// hard-coded colour is kept, but reported because it will ignore `color`.
function normalizeColors(svg, file) {
  return svg.replace(PAINT_ATTRIBUTE, (match, attribute, quote, value) => {
    const paint = value.trim();
    if (BLACK.test(paint)) return `${attribute}=${quote}currentColor${quote}`;
    if (!KEEP_PAINT.test(paint)) console.warn(`${file}: ${attribute}="${paint}" is hard-coded and will ignore the CSS color.`);
    return match;
  });
}

// Remove decorative IDs so repeated icons do not duplicate document IDs. IDs
// that are referenced (clipPath, gradients, <use>) are kept but prefixed with
// the component name so different icons cannot collide.
function scopeIds(svg, name, file) {
  if (/<style\b/i.test(svg)) {
    console.warn(`${file}: contains <style>; its IDs and classes are left untouched and apply document-wide.`);
    return svg;
  }
  const referenced = new Set();
  for (const [, id] of svg.matchAll(/url\(\s*["']?#([^"')\s]+)/g)) referenced.add(id);
  for (const [, id] of svg.matchAll(/\bhref\s*=\s*["']#([^"']+)["']/g)) referenced.add(id);
  const prefixed = id => `${name}-${id}`;
  return svg
    .replace(/\s+id\s*=\s*(["'])(.*?)\1/g, (match, quote, id) =>
      referenced.has(id) ? ` id=${quote}${prefixed(id)}${quote}` : '')
    .replace(/url\(\s*(["']?)#([^"')\s]+)\1?\s*\)/g, (match, quote, id) => `url(#${prefixed(id)})`)
    .replace(/\bhref\s*=\s*(["'])#([^"']+)\1/g, (match, quote, id) => `href=${quote}#${prefixed(id)}${quote}`);
}

function usePublicProps(code) {
  code = replaceOrThrow(code, /import type \{ SVGProps \} from "react";\n/, 'import type { IconProps } from "../types.js";\n', 'SVGProps import');
  code = replaceOrThrow(code, /interface SVGRProps \{[^}]*\}\n/, '', 'SVGRProps interface');
  code = replaceOrThrow(code, /SVGProps<SVGSVGElement> & SVGRProps/, 'IconProps', 'props type');
  return replaceOrThrow(code, /= forwardRef\(/g, '= /*#__PURE__*/forwardRef(', 'forwardRef call');
}

export async function generate(input, output) {
  const files = (await readdir(input)).filter(file => SVG_EXTENSION.test(file)).sort();
  const names = new Set();
  const components = [];
  for (const file of files) {
    const name = componentName(file);
    if (names.has(name)) throw new Error(`Duplicate component name: ${name}`);
    names.add(name);
    const svg = await readFile(resolve(input, file), 'utf8');
    const rootTag = svg.match(/<svg\b[^>]*>/i)?.[0] ?? '';
    if (!/\sviewBox\s*=/.test(rootTag)) throw new Error(`${file} needs a viewBox on its root <svg> for scalable rendering.`);
    const prepared = normalizeColors(scopeIds(svg, name, file), file);
    const code = await transform(prepared, {
      plugins: ['@svgr/plugin-jsx'],
      typescript: true,
      icon: true,
      ref: true,
      titleProp: true,
      expandProps: 'end',
      svgProps: { focusable: 'false' },
    }, { componentName: name });
    components.push([name, usePublicProps(code)]);
  }
  await mkdir(output, { recursive: true });
  await rm(resolve(output, 'icons'), { recursive: true, force: true });
  await mkdir(resolve(output, 'icons'), { recursive: true });
  for (const [name, code] of components) await writeFile(resolve(output, 'icons', `${name}.tsx`), code + '\n');
  await writeFile(resolve(output, 'index.ts'), '// Generated by scripts/generate.mjs. Do not edit.\n' +
    'export type { IconProps } from "./types.js";\n' +
    components.map(([name]) => `export { default as ${name} } from "./icons/${name}.js";`).join('\n') + '\n');
  return components.map(([name]) => name);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const names = await generate(resolve('icons'), resolve('src'));
  console.log(`Generated ${names.length} icons.${names.length ? '' : ' Add your SVG artwork to icons/ to populate the library.'}`);
}
